import "~/libs/ui/theming/unistyles";
import "./global.css";

import { Style } from "~/libs/ui/theming";

export const metadata = {
  description: "Generated by create-nx-workspace",
  title: "Welcome to web",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Style>{children}</Style>
      </body>
    </html>
  );
}
